/**
 * Creates web/.env.local from the project root .env
 * Run from project root: node scripts/sync-web-env.js
 */

const fs = require("fs");
const path = require("path");

const ROOT = path.join(__dirname, "..");
const rootEnv = path.join(ROOT, ".env");
const webEnv = path.join(ROOT, "web", ".env.local");

function loadEnv(file) {
  const env = {};
  if (!fs.existsSync(file)) return env;
  for (const line of fs.readFileSync(file, "utf8").split("\n")) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) continue;
    const eq = trimmed.indexOf("=");
    if (eq === -1) continue;
    env[trimmed.slice(0, eq).trim()] = trimmed.slice(eq + 1).trim();
  }
  return env;
}

const env = loadEnv(rootEnv);

const required = ["VAPI_API_KEY", "VAPI_PUBLIC_KEY", "VAPI_ASSISTANT_ID"];
for (const key of required) {
  if (!env[key] || env[key].includes("your_")) {
    console.error(`\nMissing ${key} in root .env\n`);
    process.exit(1);
  }
}

const content = `# Auto-generated by scripts/sync-web-env.js — do not commit
VAPI_API_KEY=${env.VAPI_API_KEY}
VAPI_PHONE_NUMBER_ID=${env.VAPI_PHONE_NUMBER_ID || ""}
NEXT_PUBLIC_VAPI_PUBLIC_KEY=${env.NEXT_PUBLIC_VAPI_PUBLIC_KEY || env.VAPI_PUBLIC_KEY}
NEXT_PUBLIC_VAPI_ASSISTANT_ID=${env.VAPI_ASSISTANT_ID}
`;

fs.writeFileSync(webEnv, content);
console.log("\nCreated web/.env.local");
if (!env.VAPI_PHONE_NUMBER_ID) {
  console.log("Note: VAPI_PHONE_NUMBER_ID is empty — outbound dialer needs it (next step).\n");
} else {
  console.log("Phone number ID synced.\n");
}
